job_environments:
  common_environment: &common_environment
    CONTAINER_PREFIX: planet4-flibble
    APP_HOSTPATH: flibble
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: www-dev.greenpeace.org
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GCLOUD_CLUSTER: p4-development
    GOOGLE_PROJECT_ID: planet-4-151612
    HELM_NAMESPACE: develop
    HELM_RELEASE: planet4-flibble
    NEWRELIC_APPNAME: P4 Flibble Development
    WP_DB_NAME: planet4-flibble_wordpress_develop
    WP_STATELESS_BUCKET: planet4-flibble-stateless-develop
  release_build_env: &release_build_env
    GOOGLE_PROJECT_ID: planet4-production
  release_environment: &release_environment
    APP_ENVIRONMENT: staging
    APP_HOSTNAME: www-stage.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: flibble
    HELM_RELEASE: planet4-flibble-release
    NEWRELIC_APPNAME: P4 Flibble Release
    WP_DB_NAME: planet4-flibble_wordpress_release
    WP_STATELESS_BUCKET: planet4-flibble-stateless-release
  production_environment: &production_environment
    APP_HOSTNAME: www.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: flibble
    HELM_RELEASE: planet4-flibble-master
    NEWRELIC_APPNAME: P4 Flibble Production
    WP_DB_NAME: planet4-flibble_wordpress_master
    WP_STATELESS_BUCKET: planet4-flibble-stateless
